# Permalinks
permalink:        pretty

# Setup
title:            What's Left
tagline:          The Jekyll Butler
url:              http://citizenspress.github.io/whatsleft
paginate:         1
baseurl:          ''
author:
  name:           CPress
  url:            https://twitter.com/leftnewsorg
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
